### ISSUE TITLE
Navigation bar overlap the calendar

### ISSUE THREAD

**Issue by finddoc** [lyahdav/LIYDateTimePicker#6]
When I subclass the LIYDateTimePicker and push the subclassed controller from previous navigation controller, the navigator bar overlap the calendar view as attached.

![ios simulator screen shot may 20 2015 10 42 14 am](https://cloud.githubusercontent.com/assets/1164404/7718009/1e1e0a2e-fedd-11e4-8703-0e626d949aa5.png)

**Comment by lyahdav** [comment]
I'll try to fix this sometime soon. For now, I'm pretty sure if you change your navigation bar to not be transparent it should fix this issue.

**Comment by finddoc** [comment]
Still not work, will it related to I use storyboard with the subclassed LIYDateTimePickerViewController? Thanks.

**Comment by finddoc** [comment]
I use the traditional way to set the self.edgesForExtendedLayout = UIRectEdgeNone and it solved now.
